metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: bonds_majors
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - TLT
      - IEF
      - IEI
      - SHY
      - BND
      - AGG
      - LQD
      - HYG
      - IGSB
      - TIP

timeframes: ["1d", "1w"]

strategies: []
