metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: commodities_majors
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - GLD
      - SLV
      - PPLT
      - USO
      - UNG
      - DBC
      - DBA
      - DBB
      - GC=F
      - SI=F
      - CL=F
      - NG=F
      - HG=F
      - ZC=F
      - ZS=F
      - ZW=F

timeframes: ["1d", "1w"]

strategies: []
