metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: crypto_majors
    source: binance
    exchange: binance
    quote: USDT
    fees: 0.0006
    slippage: 0.0005
    symbols:
      - BTC/USDT
      - ETH/USDT
      - BNB/USDT
      - SOL/USDT
      - XRP/USDT
      - ADA/USDT
      - DOGE/USDT
      - TRX/USDT
      - TON/USDT
      - DOT/USDT
      - AVAX/USDT
      - LINK/USDT
      - MATIC/USDT
      - LTC/USDT
      - BCH/USDT

timeframes: ["1d", "4h", "1h"]

strategies: []
