metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 1
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: indices_majors
    source: tiingo
    fees: 0.0005
    slippage: 0.0005
    symbols:
      # Use ETF proxies with stable daily data from Tiingo
      - SPY   # S&P 500
      - QQQ   # Nasdaq 100
      - DIA   # Dow Jones Industrial Average
      - IWM   # Russell 2000
      - EFA   # MSCI EAFE
      - EEM   # MSCI Emerging Markets
      - VGK   # Europe
      - VPL   # Pacific
      - EWJ   # Japan
      - EWU   # UK
      - EWG   # Germany
      - EWQ   # France
      - FXI   # China large-cap
      - INDA  # India
      - EWZ   # Brazil

timeframes: ["1d"]

strategies: []
