metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: large_cap_usa
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - AAPL
      - MSFT
      - GOOGL
      - GOOG
      - AMZN
      - META
      - NFLX
      - TSLA
      - NVDA
      - AMD
      - INTC
      - QCOM
      - AVGO
      - TXN
      - MU
      - AMAT
      - LRCX
      - KLAC
      - MRVL
      - ADI
      - MCHP
      - ADBE
      - CRM
      - ORCL
      - IBM
      - ACN
      - NOW
      - INTU
      - CSCO
      - VMW
      - TEAM
      - DDOG
      - SNOW
      - CRWD
      - ZS
      - OKTA
      - SPLK
      - WDAY
      - VEEV
      - DOCU
      - ZM
      - TWLO
      - NET
      - FSLY
      - DBX
      - BOX
      - WORK
      - UBER
      - LYFT
      - ABNB
      - DASH
      - RBLX
      - PINS
      - SNAP
      - TWTR
      - SQ
      - PYPL
      - SHOP
      - SPOT
      - ROKU
      - ZI
      - ESTC
      - MDB
      - PLTR
      - AI
      - C3AI
      - PATH
      - SMCI
      - DELL
      - HPQ
      - HPE
      - NTAP
      - WDC
      - STX
      - PSTG
      - NTNX
      - VRSN
      - AKAM
      - CDNS
      - SNPS
      - ANSS
      - ADSK
      - FTNT
      - PANW
      - CHKP
      - CYBR
      - TENB
      - RPD
      - QLYS
      - VRNS
      - MIME
      - FEYE
      - PFPT
      - EVBG
      - CGNX
      - TER
      - COHU
      - FORM
      - MKSI
      - ONTO
      - ACLS
      - UCTT
      - PLAB
      - NVMI
      - ICHR
      - CRUS
      - SWKS
      - QRVO
      - MPWR
      - MTSI
      - SLAB
      - SITM
      - DIOD
      - WOLF
      - AMBA
      - ALGM
      - SMTC
      - POWI
      - VICR
      - ENTG
      - DXPE
      - DXCM
      - CFLT
      - CEG
      - CECO
      - ATEC
      - LUNR
      - MELI
      - MNDY
      - APPN
      - ALVO
      - MORN
      - HOOD
      - PDD
      - XMTR
      - MSTR
      - GCT
      - BLUE
      - LFMD
      - BKNG
      - APGE
      - ROAD
      - APP
      - ARVN
      - TNDM
      - CGON
      - ADPT
      - TRUP
      - CWST
      - CALX
      - FSLR
      - PI
      - HWKN
      - PSMT
      - FCFS
      - MGRC
      - COKE
      - DORM
      - LOPE
      - COST
      - CVCO
      - IPAR
      - CSWI
      - UTHR
      - YELP
      - ATRO
      - AIOT
      - ARQT
      - INTA
      - ATAT
      - MTSR
      - ANGO
      - RR
      - ALHC
      - SLNO
      - PDEX
      - OPOF
      - SENEB
      - CME
      - ORLY
      - CRWV
      - GH
      - RYTM
      - TARS
      - WLFC
      - FTAI
      - AMSC

timeframes: ["1d"]

strategies: []
