metric: sortino
engine: vectorbt
asset_workers: 4
param_workers: 2
max_fetch_concurrency: 2
cache_dir: .cache/data

collections:
  - name: small_cap_growth
    source: yfinance
    fees: 0.0005
    slippage: 0.0005
    symbols:
      - AFRM
      - SOFI
      - HOOD
      - UPST
      - LC
      - COIN
      - SI
      - MSTR
      - OPFI
      - KRMN
      - TLN
      - ME
      - AUR
      - RGTI
      - SYM
      - APLT
      - MARA
      - SMWB
      - DTSS
      - IMNM
      - GERN
      - VTSI
      - LUNR
      - APPN
      - ALVO
      - ARVN
      - TNDM
      - TRUP
      - CWST
      - CALX
      - PI
      - ISRG
      - DXCM
      - TDOC
      - DOCU
      - HIMS
      - ONEM
      - AMWL
      - OSCR
      - MRNA
      - BNTX
      - NVAX
      - OCGN
      - INO
      - SRNE
      - VXRT
      - GEVO
      - CODX
      - QDEL
      - DVAX
      - IOVA
      - TXMD
      - CERC
      - ADVM
      - DARE
      - KERN
      - XERS
      - ATOS
      - CTMX
      - PROG
      - ADMA
      - SESN
      - AXSM
      - PTCT
      - ALNY
      - BMRN
      - TECH
      - RARE
      - FOLD
      - BLUE
      - CRSP
      - EDIT
      - NTLA
      - BEAM
      - VERV
      - SGMO
      - FATE
      - BLFS
      - CDNA
      - ARCT
      - DMTK
      - VCYT
      - PACB
      - NVTA
      - TWST
      - NTRA
      - GH
      - CDXS
      - AGIO
      - ARQL
      - APLS
      - AVXL
      - CBIO
      - ACAD
      - HZNP
      - JAZZ
      - UTHR
      - NBIX
      - SAGE
      - INCY
      - EXEL
      - BGNE
      - ZLAB
      - RGNX
      - IMMU
      - SGEN
      - BPMC
      - MRUS
      - CPRX
      - VCEL
      - CAPR
      - MEDP
      - VKTX
      - ACLX
      - NVCR
      - TMDX
      - VECO
      - BHVN
      - AOSL
      - CELH
      - SEZL
      - ALLO
      - PRAX
      - RCAT
      - OTLK
      - CENX
      - PSNL
      - NSIT
      - CHRS
      - SIGA
      - ACIU
      - PERI
      - STNE
      - LILA
      - ALTI
      - INDV
      - CEVA
      - SPNS
      - CFB
      - LWAY
      - CRBP
      - FEIM
      - PLAB
      - DSP
      - PNTG
      - IDYA
      - ENTG
      - RMBS
      - TSAT
      - HALO
      - OMER
      - ADUS
      - LMAT
      - FELE
      - APOG
      - CRL
      - CBLL
      - COOP

timeframes: ["1d"]

strategies: []
