# Markdownlint configuration for enterprise documentation standards
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD013 - Line length (disabled for flexibility in tables/code)
MD013: false

# MD033 - Inline HTML (allow for enhanced documentation)
MD033:
  allowed_elements: ["details", "summary", "br", "sub", "sup", "img"]

# MD034 - Bare URL used (allow for quick documentation)
MD034: false

# MD040 - Fenced code blocks should have a language specified
MD040: false

# MD041 - First line in file should be a top level heading
MD041: true

# MD046 - Code block style (fenced)
MD046:
  style: "fenced"

# MD048 - Code fence style (backtick)
MD048:
  style: "backtick"
