# Markdownlint configuration for development flexibility
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable strict formatting rules that cause CI issues
MD013: false  # Line length (disabled for flexibility in tables/code)
MD022: false  # Headings should be surrounded by blank lines
MD031: false  # Fenced code blocks should be surrounded by blank lines
MD032: false  # Lists should be surrounded by blank lines

# Allow common development patterns
MD033:
  allowed_elements: ["details", "summary", "br", "sub", "sup", "img"]
MD034: false  # Bare URL used (allow for quick documentation)
MD040: false  # Fenced code blocks should have a language specified
MD041: false  # First line in file should be a top level heading (allow flexibility)

# Code block preferences
MD046:
  style: "fenced"
MD048:
  style: "backtick"

# Allow trailing punctuation in headings (common in documentation)
MD026: false

# Allow multiple consecutive blank lines
MD012: false

# Allow trailing spaces
MD009: false

# Allow list marker spacing flexibility
MD030: false

# Allow duplicate headings (common in API docs)
MD024: false
