repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        exclude: '^exports/'
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml

  # Python formatting - Ruff (matches GitHub workflow check)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-format
        # Auto-fix in pre-commit, but GitHub runs --check

  # Python import sorting - isort (matches GitHub workflow)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile, black, --skip, quant-strategies]
        # Auto-fix in pre-commit, but GitHub runs --check-only

  # Python linting - Ruff (matches GitHub workflow)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix]
        # Auto-fix in pre-commit, but GitHub runs without --fix

  # Tests (temporarily disabled due to import issues)
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       # Run tests fast - no coverage report in pre-commit

  # Markdown linting (aligned with GitHub workflow)
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
        args: ["**/*.md", "!.venv/**/*.md", "!node_modules/**/*.md", "!exports/**/*.md"]

  # Additional checks disabled - GitHub provides these automatically:
  # - MyPy (type checking)
  # - Bandit (security scanning - handled by GitHub CodeQL)
  # - Safety (dependency scanning - handled by GitHub Dependabot)
