repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Markdown lint (dockerized markdownlint-cli to avoid local runtime issues)
  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint (docker_image)
        language: docker_image
        files: '^(README\.md|docs/.*\.md|CHANGELOG\.md|CONTRIBUTING\.md|CODE_OF_CONDUCT\.md|SECURITY\.md|GOVERNANCE\.md)$'
        entry: ghcr.io/igorshubovych/markdownlint-cli:latest
        args: ["markdownlint", "-c", "/src/.markdownlint.json"]
        pass_filenames: true
        require_serial: true

  # Run tests with coverage >= 80% (if tests present)
  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest with coverage
        entry: bash -lc 'if compgen -G "tests/*.py" > /dev/null; then SKIP_PANDAS_TESTS=1 poetry run pytest -q --maxfail=1 --disable-warnings --cov=src.backtest.results_cache --cov=src.utils.http --cov=src.reporting.html --cov-report=term-missing --cov-fail-under=80; else echo "No tests found; skipping coverage"; fi'
        language: system
        pass_filenames: false
