services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: quant-system:latest
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      # Override STRATEGIES_PATH or DATA_CACHE_DIR via env if needed
      - STRATEGIES_PATH=/ext/strategies
      - DATA_CACHE_DIR=/app/.cache/data
      - PATH=/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    env_file:
      - .env
    volumes:
      - ./:/app
      # Mount your external strategies repo here
      - /Users/manuelheck/Documents/Websites/Private/quant/quant-strategies/algorithms/python:/ext/strategies:ro
    working_dir: /app
    command: ["sleep", "infinity"]
