services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: quant-postgres
    environment:
      - POSTGRES_DB=quant_system
      - POSTGRES_USER=quantuser
      - POSTGRES_PASSWORD=quantpass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped

  # Local quant system with production features
  quant:
    build:
      context: .
      dockerfile: DOCKERFILE
      target: development
    image: quant-system:local
    container_name: quant-system
    environment:
      - ENVIRONMENT=local
      - CACHE_DIR=/app/cache
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://quantuser:quantpass@postgres:5432/quant_system
    volumes:
      - ./cache:/app/cache
      - ./exports:/app/exports
      - ./reports_output:/app/reports_output
      - ./logs:/app/logs
      - ./config:/app/config:ro
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: ["bash"]

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
