[tool.poetry]
name = "quant-system"
version = "0.1.0"
description = "A Python-based Quant Trading System with FastAPI, Backtrader, and yfinance"
authors = ["LouisLetcher <heck.manu@icloud.com>"]
license = "Proprietary"
readme = "README.md"
packages = [{ include = "src", from = "." }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115"
uvicorn = "^0.34"
pydantic = "^2.11"
yfinance = "^0.2"
yfinance-cache = "^0.7"
pandas = "^2.2"
numpy = "^2.2"
matplotlib = "^3.10"
jinja2 = "^3.1"
sqlalchemy = "^2.0"
asyncpg = "^0.30"
alembic = "^1.15"
bayesian-optimization = "^2.0"
backtesting = "^0.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
black = "^25.1"
isort = "^6.0"
pre-commit = "^4.2"
ruff = "^0.11"

[tool.poetry.scripts]
start = "uvicorn src.api.main:app --host 0.0.0.0 --port 8000"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"