[tool.ruff]
# Enable flake8-bugbear rules
select = ["E", "F", "B", "I"]
ignore = []
line-length = 88  # Match black's default line length
target-version = "py311"  # Specify your target Python version

# Allow autofix for all enabled rules that support it
fixable = ["ALL"]
unfixable = []

# Exclude directories and files
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "venv",
    ".env",
]

# Sort imports
[tool.ruff.isort]
known-first-party = ["src"]

# Per-file rule ignoring
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py files
