name: CI Matrix

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: [false, true]
    env:
      COMPOSE_PROFILES: ${{ matrix.redis && 'redis' || '' }}
      USE_REDIS_RECENT: ${{ matrix.redis }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Build compose image
        run: |
          docker compose build quant
      - name: Run pre-commit (lint + tests)
        run: |
          pre-commit run -a
