name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Format check
        run: poetry run ruff format --check .

      - name: Lint & Import sort
        run: poetry run ruff check .

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md !.venv/**/*.md !node_modules/**/*.md !exports/**/*.md'

      - name: Test with Coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=10
          echo "Coverage report generated"

      - name: Upload Coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Build
        run: poetry build
