name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.0"

      - name: Install dependencies
        run: poetry install

      - name: Format check
        run: poetry run black --check .

      - name: Import sort check
        run: poetry run isort --check-only .

      - name: Lint
        run: poetry run ruff check .

      # Type check disabled for showcase project
      # - name: Type check
      #   run: poetry run mypy src/

      - name: Security check
        run: poetry run bandit -r src/

      - name: Test
        run: poetry run pytest

      - name: Build
        run: poetry build
