name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Format check
        run: poetry run black --check .

      - name: Import sort check
        run: poetry run isort --check-only .

      - name: Lint
        run: poetry run ruff check .

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md !.venv/**/*.md !node_modules/**/*.md'

      - name: Test
        run: poetry run pytest

      - name: Build
        run: poetry build
